name: 'telegram_medical_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'telegram_medical_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  telegram_medical_pipeline:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

# Configuring seeds
seeds:
  telegram_medical_pipeline:
    +schema: raw

# Configuring snapshots
snapshots:
  telegram_medical_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Configuring tests
tests:
  telegram_medical_pipeline:
    +schema: test_results

# Configuring documentation
docs-paths: ["docs"]

# Configuring packages
packages-install-path: "dbt_packages"

# Configuring vars
vars:
  # Add any project-level variables here
  project_start_date: '2024-01-01'
  time_zone: 'UTC'

# Configuring models with specific configurations
models:
  telegram_medical_pipeline:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      dim_channels:
        +materialized: table
        +schema: marts
      dim_dates:
        +materialized: table
        +schema: marts
      fct_messages:
        +materialized: table
        +schema: marts 